import { v4 as uuidv4 } from "uuid";
import { students } from "./schema";

export const allTeachers = [
  {
    t_id: uuidv4(),
    email: "bgokulnaath@gmail.com",
    name: "B Gokulnaath",
    status: "approved",
  },
];

export const seedStudents: (typeof students.$inferInsert)[] = [
  {
    student_name: "Sonu",
    class: 5,
    division: "A",
    roll_number: 1,
    admission_number: 1001,
    aadhar_number: "123456789001",
    mother_name: "Lakshmi Ravi",
    dob: "2014-05-10",
    father_name: "Ravi Kumar",
    panchayat: "Thrissur Panchayat",
    ward: 5,
    place: "Thrissur",
    house_name: "Krishna Nivas",
    gender: "Male",
    religion: "Hindu",
    caste: "General",
    poverty_line: "APL",
    medium: "English",
    phone_number: "9876543210",
    house_ownership: "Own House",
    house_type: "Concrete",
    father_educational_qualification: "Graduate",
    father_job: "Teacher",
    mother_educational_qualification: "Graduate",
    mother_job: "Homemaker",
    other_family_members: "Grandmother",
    annual_income: 250000,
    study_room: "Yes",
    study_table: "Yes",
    study_time: 2,
    difficulties_obstacles: "None",
    special_study_support: "Tuition",
    parental_involvement: "High",
    child_health_status: "Healthy",
    child_sme_status:
      "Emotionally stable and socially active. Participates well in class discussions and group activities. Shows positive interaction with peers.",
  },

  {
    student_name: "Gagan",
    class: 5,
    division: "A",
    roll_number: 2,
    admission_number: 1002,
    aadhar_number: "123456789002",
    mother_name: "Anitha Suresh",
    dob: "2014-07-15",
    father_name: "Suresh Babu",
    panchayat: "Thrissur Panchayat",
    ward: 6,
    place: "Thrissur",
    house_name: "Sree Bhavan",
    gender: "Female",
    religion: "Hindu",
    caste: "OBC",
    poverty_line: "BPL",
    medium: "Malayalam",
    phone_number: "9876543211",
    house_ownership: "Rented House",
    house_type: "Tile-Roofed House",
    father_educational_qualification: "Plus Two",
    father_job: "Driver",
    mother_educational_qualification: "SSLC",
    mother_job: "Tailor",
    other_family_members: "Grandfather",
    annual_income: 150000,
    study_room: "No",
    study_table: "No",
    study_time: 1,
    difficulties_obstacles: "Lack of quiet space",
    special_study_support: "School mentoring",
    parental_involvement: "Medium",
    child_health_status: "Healthy",
    child_sme_status:
      "Slightly reserved but cooperative. Needs encouragement in group settings. Emotionally sensitive but responds well to teacher support.",
  },

  {
    student_name: "Sari",
    class: 5,
    division: "B",
    roll_number: 1,
    admission_number: 1003,
    aadhar_number: "123456789003",
    mother_name: "Meera Nair",
    dob: "2014-03-22",
    father_name: "Rajeev Nair",
    panchayat: "Kuttur Panchayat",
    ward: 2,
    place: "Kuttur",
    house_name: "Megham Villa",
    gender: "Male",
    religion: "Hindu",
    caste: "General",
    poverty_line: "APL",
    medium: "English",
    phone_number: "9876543212",
    house_ownership: "Own House",
    house_type: "Concrete",
    father_educational_qualification: "Post Graduate",
    father_job: "Bank Officer",
    mother_educational_qualification: "Graduate",
    mother_job: "Teacher",
    other_family_members: "None",
    annual_income: 600000,
    study_room: "Yes",
    study_table: "Yes",
    study_time: 3,
    difficulties_obstacles: "None",
    special_study_support: "Online courses",
    parental_involvement: "High",
    child_health_status: "Healthy",
    child_sme_status:
      "Confident and expressive. Maintains healthy peer relationships. Demonstrates good emotional regulation and classroom engagement.",
  },

  {
    student_name: "Kannan",
    class: 6,
    division: "A",
    roll_number: 1,
    admission_number: 1004,
    aadhar_number: "123456789004",
    mother_name: "Rashmi Devi",
    dob: "2013-11-11",
    father_name: "Manoj Kumar",
    panchayat: "Cherpu Panchayat",
    ward: 8,
    place: "Cherpu",
    house_name: "Ananda Bhavan",
    gender: "Female",
    religion: "Christian",
    caste: "General",
    poverty_line: "APL",
    medium: "English",
    phone_number: "9876543213",
    house_ownership: "Own House",
    house_type: "Concrete",
    father_educational_qualification: "Graduate",
    father_job: "Engineer",
    mother_educational_qualification: "Graduate",
    mother_job: "Nurse",
    other_family_members: "Younger brother",
    annual_income: 700000,
    study_room: "Yes",
    study_table: "Yes",
    study_time: 2,
    difficulties_obstacles: "None",
    special_study_support: "Coaching class",
    parental_involvement: "High",
    child_health_status: "Healthy",
    child_sme_status:
      "Friendly and socially adaptable. Shows leadership qualities during group tasks. Emotionally balanced and respectful towards others.",
  },

  {
    student_name: "Karthikeya",
    class: 6,
    division: "A",
    roll_number: 2,
    admission_number: 1005,
    aadhar_number: "123456789005",
    mother_name: "Shalini Varma",
    dob: "2013-09-09",
    father_name: "Prakash Varma",
    panchayat: "Cherpu Panchayat",
    ward: 4,
    place: "Cherpu",
    house_name: "Varma House",
    gender: "Male",
    religion: "Hindu",
    caste: "OBC",
    poverty_line: "BPL",
    medium: "Malayalam",
    phone_number: "9876543214",
    house_ownership: "Rented House",
    house_type: "Tile-Roofed House",
    father_educational_qualification: "Plus Two",
    father_job: "Electrician",
    mother_educational_qualification: "SSLC",
    mother_job: "Homemaker",
    other_family_members: "Grandmother",
    annual_income: 180000,
    study_room: "No",
    study_table: "Yes",
    study_time: 1,
    difficulties_obstacles: "Financial constraints",
    special_study_support: "Scholarship",
    parental_involvement: "Medium",
    child_health_status: "Healthy",
    child_sme_status:
      "Quiet and observant. Occasionally hesitant in participation but improves with guidance. Emotionally stable with supportive family background.",
  },

  {
    student_name: "Krish",
    class: 6,
    division: "B",
    roll_number: 1,
    admission_number: 1006,
    aadhar_number: "123456789006",
    mother_name: "Jaya Thomas",
    dob: "2013-01-25",
    father_name: "Thomas Mathew",
    panchayat: "Kuttur Panchayat",
    ward: 3,
    place: "Kuttur",
    house_name: "Rose Villa",
    gender: "Female",
    religion: "Christian",
    caste: "General",
    poverty_line: "APL",
    medium: "English",
    phone_number: "9876543215",
    house_ownership: "Own House",
    house_type: "Concrete",
    father_educational_qualification: "Graduate",
    father_job: "Accountant",
    mother_educational_qualification: "Graduate",
    mother_job: "Teacher",
    other_family_members: "Younger sister",
    annual_income: 500000,
    study_room: "Yes",
    study_table: "Yes",
    study_time: 3,
    difficulties_obstacles: "None",
    special_study_support: "Online learning",
    parental_involvement: "High",
    child_health_status: "Healthy",
    child_sme_status:
      "Highly interactive and enthusiastic learner. Displays empathy towards classmates. Emotionally confident and motivated.",
  },

  {
    student_name: "Aathmaj",
    class: 7,
    division: "A",
    roll_number: 1,
    admission_number: 1007,
    aadhar_number: "123456789007",
    mother_name: "Deepa Nair",
    dob: "2012-02-14",
    father_name: "Harish Nair",
    panchayat: "Thrissur Panchayat",
    ward: 7,
    place: "Thrissur",
    house_name: "Nair House",
    gender: "Male",
    religion: "Hindu",
    caste: "General",
    poverty_line: "APL",
    medium: "English",
    phone_number: "9876543216",
    house_ownership: "Own House",
    house_type: "Concrete",
    father_educational_qualification: "Post Graduate",
    father_job: "Doctor",
    mother_educational_qualification: "Graduate",
    mother_job: "Teacher",
    other_family_members: "Grandfather",
    annual_income: 900000,
    study_room: "Yes",
    study_table: "Yes",
    study_time: 4,
    difficulties_obstacles: "None",
    special_study_support: "Private tuition",
    parental_involvement: "High",
    child_health_status: "Healthy",
    child_sme_status:
      "Mature and responsible for age. Handles academic pressure well. Maintains strong peer connections and positive mindset.",
  },

  {
    student_name: "Jaggu",
    class: 7,
    division: "B",
    roll_number: 1,
    admission_number: 1008,
    aadhar_number: "123456789008",
    mother_name: "Rekha Menon",
    dob: "2012-06-18",
    father_name: "Anil Menon",
    panchayat: "Cherpu Panchayat",
    ward: 1,
    place: "Cherpu",
    house_name: "Menon Villa",
    gender: "Female",
    religion: "Hindu",
    caste: "OBC",
    poverty_line: "BPL",
    medium: "Malayalam",
    phone_number: "9876543217",
    house_ownership: "Rented House",
    house_type: "Tile-Roofed House",
    father_educational_qualification: "Plus Two",
    father_job: "Shopkeeper",
    mother_educational_qualification: "SSLC",
    mother_job: "Tailor",
    other_family_members: "Grandmother",
    annual_income: 200000,
    study_room: "No",
    study_table: "No",
    study_time: 1,
    difficulties_obstacles: "Space constraints",
    special_study_support: "Government scholarship",
    parental_involvement: "Medium",
    child_health_status: "Healthy",
    child_sme_status:
      "Needs occasional emotional reassurance. Socially cooperative but shy in new environments. Responds positively to structured guidance.",
  },

  {
    student_name: "Aathmaj",
    class: 8,
    division: "A",
    roll_number: 1,
    admission_number: 1009,
    aadhar_number: "123456789009",
    mother_name: "Priya Kumar",
    dob: "2011-04-30",
    father_name: "Sunil Kumar",
    panchayat: "Thrissur Panchayat",
    ward: 9,
    place: "Thrissur",
    house_name: "Kumar Bhavan",
    gender: "Male",
    religion: "Hindu",
    caste: "General",
    poverty_line: "APL",
    medium: "English",
    phone_number: "9876543218",
    house_ownership: "Own House",
    house_type: "Concrete",
    father_educational_qualification: "Graduate",
    father_job: "Police Officer",
    mother_educational_qualification: "Graduate",
    mother_job: "Homemaker",
    other_family_members: "Younger brother",
    annual_income: 450000,
    study_room: "Yes",
    study_table: "Yes",
    study_time: 3,
    difficulties_obstacles: "None",
    special_study_support: "Coaching center",
    parental_involvement: "High",
    child_health_status: "Healthy",
    child_sme_status:
      "Self-motivated and emotionally steady. Demonstrates strong interpersonal skills. Actively participates in academic and extracurricular activities.",
  },

  {
    student_name: "Gagan",
    class: 8,
    division: "B",
    roll_number: 1,
    admission_number: 1010,
    aadhar_number: "123456789010",
    mother_name: "Anju George",
    dob: "2011-12-12",
    father_name: "George Mathew",
    panchayat: "Kuttur Panchayat",
    ward: 10,
    place: "Kuttur",
    house_name: "George Villa",
    gender: "Female",
    religion: "Christian",
    caste: "General",
    poverty_line: "APL",
    medium: "English",
    phone_number: "9876543219",
    house_ownership: "Own House",
    house_type: "Concrete",
    father_educational_qualification: "Post Graduate",
    father_job: "Professor",
    mother_educational_qualification: "Graduate",
    mother_job: "Teacher",
    other_family_members: "Younger sister",
    annual_income: 800000,
    study_room: "Yes",
    study_table: "Yes",
    study_time: 4,
    difficulties_obstacles: "None",
    special_study_support: "Advanced coaching",
    parental_involvement: "High",
    child_health_status: "Healthy",
    child_sme_status:
      "Confident communicator with healthy social bonding. Emotionally resilient and adapts well to academic challenges.",
  },
];
